#!/user/bin/tclsh
puts "enter the number of elements:"
set n [gets stdin]
set a 0
set b 1
set c 0
puts "fibonacci series:"
for  {set i 0} {$i < $n} {incr i} {
  puts $a
  set c [expr {$a + $b}]
  set a $b
  set b $c
  }
